repos:
  - repo: https://github.com/prettier/prettier
    rev: "1.14.0"
    hooks:
    - id: prettier
      args: [config ./.prettierrc]
      exclude: ".*.html"
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
