language: node_js
node_js:
  - "7"

script: npm run build:prod
after_deploy: ./node_modules/cloudflare-cli/bin/cfcli purge

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
